version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - sossickd/iog-systems-engineering
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
    labels:
      - chore
      - update
    assignees:
      - sossickd/iog-systems-engineering
