name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  workflow:
    name: Reusable Workflow
    uses: LexisNexis-RBA/rsg-gh-workflows-terraform/.github/workflows/module-publish-release.yaml@main
    secrets: inherit
    with:
      module_name: terraform-kubernetes-ingress-nginx
