name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  workflow:
    name: Reusable Workflow
    uses: sossickd/rsg-gh-workflows-terraform/.github/workflows/module-pull-request.yaml@main
    secrets: inherit
    with:
      module_name: terraform-lnrs-helm-opencost
